export const enum RouteNames {
  HOME = '/',
  BOOK = '/book',
  ADDONS = '/add-ons',
  PAYMENT = '/payment',
  POLICY = '/policy',
  THANKS = '/thank-you',
  ADD_PET = '/add-pet',
  MY_ACCOUNT = '/my-account',
  APPOINTMENTS = '/appointments',
  PETS = '/pets',
  PET_DETAILS = '/pet-details',
  LOGIN = '/login',
  FORGOT_PASSWORD = '/forgotpassword',
  SIGNUP = '/signup',
  NOTFOUND = '/404',
  LOGOUT = '/logout',
  ADD_CARD = '/add-card',
  PAYMENT_METHODS = '/payment-methods'
}
